process.env.NODE_PATH = 'C:/Users/rbtki/AppData/Roaming/npm/node_modules';
require('module').Module._initPaths();

const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
        Footer, AlignmentType, HeadingLevel, BorderStyle, WidthType,
        ShadingType, PageNumber } = require('docx');
const fs = require('fs');

const border = { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' };
const borders = { top: border, bottom: border, left: border, right: border };
const hdrShade = { fill: 'D5E8F0', type: ShadingType.CLEAR };
const cm = { top: 80, bottom: 80, left: 120, right: 120 };
const W = 9026;

function cell(text, width, isHeader) {
  return new TableCell({
    borders,
    width: { size: width, type: WidthType.DXA },
    shading: isHeader ? hdrShade : undefined,
    margins: cm,
    children: [new Paragraph({ children: [new TextRun({ text: String(text), font: 'Arial', size: 18, bold: !!isHeader })] })]
  });
}

function tbl(headers, rows, widths) {
  return new Table({
    width: { size: W, type: WidthType.DXA },
    columnWidths: widths,
    rows: [
      new TableRow({ children: headers.map((h, i) => cell(h, widths[i], true)) }),
      ...rows.map(r => new TableRow({ children: r.map((d, i) => cell(d, widths[i], false)) }))
    ]
  });
}

const h1 = t => new Paragraph({ heading: HeadingLevel.HEADING_1, spacing: { before: 300, after: 120 }, children: [new TextRun({ text: t, font: 'Arial', size: 32, bold: true, color: '1F3864' })] });
const h2 = t => new Paragraph({ heading: HeadingLevel.HEADING_2, spacing: { before: 240, after: 100 }, children: [new TextRun({ text: t, font: 'Arial', size: 26, bold: true, color: '2E75B6' })] });
const h3 = t => new Paragraph({ heading: HeadingLevel.HEADING_3, spacing: { before: 180, after: 80 }, children: [new TextRun({ text: t, font: 'Arial', size: 22, bold: true, color: '2F5496' })] });
const p  = t => new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: t, font: 'Arial', size: 20 })] });
const code = t => new Paragraph({ children: [new TextRun({ text: t, font: 'Courier New', size: 17 })] });
const gap = () => new Paragraph({ children: [new TextRun('')] });
const note = t => new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: '  Note: ' + t, font: 'Arial', size: 18, italics: true, color: '595959' })] });

const cl = lines => lines.map(code);

const doc = new Document({
  styles: { default: { document: { run: { font: 'Arial', size: 20 } } } },
  sections: [{
    properties: { page: { size: { width: 11906, height: 16838 }, margin: { top: 1080, right: 1080, bottom: 1080, left: 1080 } } },
    footers: { default: new Footer({ children: [new Paragraph({ alignment: AlignmentType.RIGHT, children: [new TextRun({ text: 'RBT – SAP Vendor Portal Backend V2.0  |  Page ', font: 'Arial', size: 16, color: '595959' }), new TextRun({ children: [PageNumber.CURRENT], font: 'Arial', size: 16, color: '595959' })] })] }) },
    children: [

      // TITLE
      h1('SAP ABAP Backend – Vendor Portal'),
      h2('Step-by-Step Guide with Frontend & Middleware Alignment Fixes'),
      gap(),
      tbl(['Field','Value'],[
        ['Document Title','SAP ABAP Backend – Vendor Portal Guide'],
        ['Author Initials','RBT'],
        ['Module','MM (Material Management) + FI (Finance)'],
        ['Object Prefix','ZMM_RBT_'],
        ['Document Version','V2.0 – Final (With Alignment Fixes)'],
        ['Date','02-May-2026'],
        ['Reference FRS','GE24 – SAP ERP Portal FRS V1.1.1'],
      ],[3200,5826]),
      gap(),

      // 1
      h1('1. Vendor Portal Objective'),
      p('The Vendor Portal covers MM and FI module functionalities. It maintains vendor data and enables complete transaction visibility between the company and vendor.'),
      p('The backend covers four areas: Vendor Login | Vendor Profile | Dashboard (RFQ, PO, GR) | Financial Sheet (Invoice, Aging, Memo, Adobe Form)'),
      p('Technology Stack:  Angular 17 (Frontend)  →  Node.js/Express (Middleware RFC Bridge)  →  SAP ABAP RFC Function Modules (Backend)'),
      gap(),

      // 2
      h1('2. Naming Conventions'),
      h2('2.1 Variable Naming Standards'),
      tbl(['Variable Type','Prefix'],[['Field','WF_'],['Flag','WG_'],['Local Variable','LOC_'],['Constants','C_'],['Internal Tables','IT_'],['Work Area','WA_'],['Field Symbol','FS_'],['Select-Options','S_'],['Parameters','P_'],['Types','TY_']],[3500,5526]),
      gap(),
      h2('2.2 Object Naming Standards'),
      tbl(['Object Type','Pattern / Name'],[
        ['Package','ZMM_RBT_VEND_PORTAL'],
        ['Database Table','ZMM_RBT_<TEXT>'],
        ['Structure','ZMM_RBT_<TEXT>_S'],
        ['Table Type','ZMM_RBT_<TEXT>_T'],
        ['Function Group','ZMM_RBT_<TEXT>'],
        ['Function Module','ZMM_RBT_<TEXT>'],
        ['Adobe Form','ZF_MM_RBT_<TEXT>'],
        ['Adobe Interface','ZIF_MM_RBT_<TEXT>'],
      ],[3500,5526]),
      gap(),

      // 3
      h1('3. Complete Object List'),
      tbl(['Object Name','Object Type','Purpose'],[
        ['ZMM_RBT_VEND_PORTAL','Package','All vendor portal ABAP objects'],
        ['ZMM_RBT_VEND_LOGIN','Database Table','Vendor login credentials (Z-table)'],
        ['ZMM_RBT_PROF_S','Structure','Vendor profile fields – updated with fixes'],
        ['ZMM_RBT_DASH_S','Structure','RFQ / PO / GR row data – updated with fixes'],
        ['ZMM_RBT_INV_S','Structure','Invoice + Aging row data – updated with fixes'],
        ['ZMM_RBT_MEMO_S','Structure','Credit/Debit memo row data'],
        ['ZMM_RBT_DASH_T','Table Type','Dashboard internal table type'],
        ['ZMM_RBT_INV_T','Table Type','Invoice internal table type'],
        ['ZMM_RBT_MEMO_T','Table Type','Memo internal table type'],
        ['ZMM_RBT_VEND_PRT','Function Group','Groups all 4 Function Modules'],
        ['ZMM_RBT_VENDOR_LOGIN','RFC Function Module','Login validation (Step 6)'],
        ['ZMM_RBT_VENDOR_PROFILE','RFC Function Module','Vendor master data (Step 7)'],
        ['ZMM_RBT_VENDOR_DASHBOARD','RFC Function Module','RFQ + PO + GR (Step 8)'],
        ['ZMM_RBT_VENDOR_FINANCIAL','RFC Function Module','Invoice + Aging + Memo (Step 9)'],
        ['ZF_MM_RBT_VEND_INVOICE','Adobe Form','Printable Invoice Receipt (Step 10)'],
        ['ZIF_MM_RBT_VEND_INVOICE','Adobe Interface','Interface for invoice Adobe Form'],
      ],[2800,2500,3726]),
      p('Total: 1 Table  |  4 Structures  |  3 Table Types  |  1 Function Group  |  4 Function Modules  |  1 Adobe Form'),
      gap(),

      // 4
      h1('4. Step-by-Step Implementation'),

      h2('Step 1 – Create Package & Transport Request  |  Transaction: SE80'),
      p('1.  SE80 → right-click on object tree → Create → Package'),
      p('2.  Package Name: ZMM_RBT_VEND_PORTAL     Short Description: RBT Vendor Portal Backend'),
      p('3.  Create a new Workbench Transport Request (TR) and note the TR number'),
      p('4.  Assign ALL objects from all subsequent steps to this package and TR'),
      gap(),

      h2('Step 2 – Create Z-Table for Vendor Login  |  Transaction: SE11'),
      p('Table Name: ZMM_RBT_VEND_LOGIN     Delivery Class: A     Data Browser: Display/Maintenance Allowed'),
      gap(),
      tbl(['Field','Data Element','Key','Description'],[
        ['MANDT','MANDT','Yes','Client'],
        ['VENDOR_ID','LIFNR','Yes','Vendor Number (must match LFA1-LIFNR)'],
        ['PASSWORD','CHAR64','No','Hashed Password (64 characters)'],
        ['IS_ACTIVE','XFELD','No','Active Flag: X = Active, blank = Inactive'],
        ['LAST_LOGIN','DATUM','No','Date of Last Successful Login'],
      ],[1800,2000,800,4426]),
      p('After activating: SM30 → ZMM_RBT_VEND_LOGIN → Maintain → add test vendor records'),
      gap(),

      h2('Step 3 – Create Structures  |  Transaction: SE11'),
      p('For each: SE11 → name → Create → Category: Structure → add fields → Save → Activate → assign to TR'),
      gap(),

      h3('Structure 1: ZMM_RBT_PROF_S  –  Vendor Profile'),
      note('Fields marked [FIX] were added after frontend/middleware alignment check'),
      tbl(['Component','Data Element','Description'],[
        ['LIFNR','LIFNR','Vendor ID'],
        ['NAME1','NAME1_GP','Vendor Name'],
        ['ORT01','ORT01_GP','City'],
        ['LAND1','LAND1_GP','Country'],
        ['STRAS','STRAS_GP','Street Address'],
        ['PSTLZ','PSTLZ','Postal Code  [FIX – required by frontend]'],
        ['TELF1','TELF1','Phone Number'],
        ['SMTP_ADDR','AD_SMTPADR','Email Address'],
        ['WAERS','WAERS','Currency'],
        ['ZTERM','DZTERM','Payment Terms'],
        ['BUKRS','BUKRS','Company Code  [FIX – required by frontend]'],
        ['AKONT','AKONT','Reconciliation Account'],
        ['EKGRP','BKGRP','Purchasing Group'],
        ['STCD1','STCD1','Tax Number / Tax ID  [FIX – required by frontend]'],
      ],[2200,2300,4526]),
      gap(),

      h3('Structure 2: ZMM_RBT_DASH_S  –  Dashboard (RFQ, PO, GR)'),
      note('Fields marked [FIX] added to support gr_no, deadline date, and movement_type required by frontend'),
      tbl(['Component','Data Element','Description'],[
        ['DOC_TYPE','CHAR3','Document Type: RFQ / PO / GR'],
        ['EBELN','EBELN','Document Number (RFQ/PO number)'],
        ['BEDAT','BEDAT','Document Date'],
        ['MATNR','MATNR','Material Number'],
        ['TXZ01','TXZ01','Material Description'],
        ['MENGE','MENGE_D','Quantity'],
        ['MEINS','MEINS','Unit of Measure'],
        ['NETPR','BPREI','Net Price per unit'],
        ['WAERS','WAERS','Currency'],
        ['WERKS','WERKS_D','Plant'],
        ['LGORT','LGORT_D','Storage Location'],
        ['ELIKZ','ELIKZ','Delivery Complete Flag (X = complete)'],
        ['EINDT','EINDT','Deadline/Delivery Date  [FIX – for RFQ deadline & PO delivery_date]'],
        ['BUDAT','BUDAT','Posting Date (used for GR)'],
        ['MBLNR','MBLNR','Material Document Number / GR Number  [FIX – gr_no]'],
        ['BWART','BWART','Movement Type (101 = GR for PO)  [FIX – movement_type]'],
      ],[2200,2300,4526]),
      gap(),

      h3('Structure 3: ZMM_RBT_INV_S  –  Invoice and Aging'),
      note('7 fields added after alignment check – frontend requires GJAHR, BLART, MWSKZ, XBLNR, SGTXT, LIFNR, STATUS'),
      tbl(['Component','Data Element','Description'],[
        ['BELNR','BELNR_D','Invoice Document Number'],
        ['GJAHR','GJAHR','Fiscal Year  [FIX]'],
        ['BLDAT','BLDAT','Billing Date (Invoice Date)'],
        ['BUDAT','BUDAT','Posting Date'],
        ['EBELN','EBELN','Reference Purchase Order Number'],
        ['LIFNR','LIFNR','Vendor Number  [FIX]'],
        ['BLART','BLART','Document Type: RE=Invoice, KG=Credit, KL=Debit  [FIX]'],
        ['WRBTR','WRBTR','Invoice Amount'],
        ['WAERS','WAERS','Currency'],
        ['ZFBDT','DZFBDT','Due Date'],
        ['AGING_DAYS','INT4','Aging = Billing Date minus Due Date (FRS formula)'],
        ['SHKZG','SHKZG','Debit/Credit Indicator (H or S)'],
        ['ZLSCH','DZLSCH','Payment Method'],
        ['MWSKZ','MWSKZ','Tax Code  [FIX]'],
        ['XBLNR','XBLNR','External Reference / Vendor Invoice Number  [FIX]'],
        ['SGTXT','SGTXT','Item Text / Description  [FIX]'],
        ['AUGDT','AUGDT','Clearing Date (filled only when paid)'],
        ['STATUS','CHAR1','O = Open (from BSIK), C = Cleared (from BSAK)  [FIX]'],
      ],[2200,2300,4526]),
      gap(),

      h3('Structure 4: ZMM_RBT_MEMO_S  –  Credit/Debit Memo'),
      tbl(['Component','Data Element','Description'],[
        ['BELNR','BELNR_D','Memo Document Number'],
        ['BLDAT','BLDAT','Document Date'],
        ['BUDAT','BUDAT','Posting Date'],
        ['BLART','BLART','Document Type: KG = Credit Memo, KL = Debit Memo'],
        ['WRBTR','WRBTR','Amount'],
        ['WAERS','WAERS','Currency'],
        ['SGTXT','SGTXT','Item Text / Description'],
        ['SHKZG','SHKZG','H = Debit, S = Credit'],
      ],[2200,2300,4526]),
      gap(),

      h2('Step 4 – Create Table Types  |  Transaction: SE11'),
      p('SE11 → name → Create → Category: Table Type → Line Type = structure name → Save → Activate'),
      tbl(['Table Type','Line Type','Description'],[
        ['ZMM_RBT_DASH_T','ZMM_RBT_DASH_S','Dashboard table type (RFQ, PO, GR)'],
        ['ZMM_RBT_INV_T','ZMM_RBT_INV_S','Invoice and Aging table type'],
        ['ZMM_RBT_MEMO_T','ZMM_RBT_MEMO_S','Credit and Debit Memo table type'],
      ],[2800,2800,3426]),
      gap(),

      h2('Step 5 – Create Function Group  |  Transaction: SE37'),
      p('Function Group: ZMM_RBT_VEND_PRT     Short Text: RBT Vendor Portal     Package: ZMM_RBT_VEND_PORTAL'),
      p('All 4 Function Modules (Steps 6–9) must belong to this Function Group.'),
      gap(),

      h2('Step 6 – FM 1: ZMM_RBT_VENDOR_LOGIN  |  Processing Type: RFC  |  FRS 3.2.1'),
      tbl(['Parameter','Direction','Type','Description'],[
        ['IV_VENDOR_ID','Import','LIFNR','Vendor ID from portal login'],
        ['IV_PASSWORD','Import','CHAR64','Password from portal login'],
        ['EV_RESULT','Export','CHAR1','S = Success, E = Error'],
        ['EV_MESSAGE','Export','CHAR100','Response message to portal'],
      ],[2200,1400,1600,3826]),
      gap(),
      ...cl([
        'FUNCTION ZMM_RBT_VENDOR_LOGIN.',
        '  DATA: LOC_LIFNR TYPE lfa1-lifnr,',
        '        WA_LOGIN  TYPE zmm_rbt_vend_login.',
        '',
        '  " Step 1: Check vendor exists in SAP standard table LFA1',
        '  SELECT SINGLE lifnr INTO LOC_LIFNR',
        '    FROM lfa1 WHERE lifnr = iv_vendor_id.',
        '  IF sy-subrc <> 0.',
        "    ev_result = 'E'.",
        "    ev_message = 'Vendor ID does not exist in the system'.",
        '    RETURN.',
        '  ENDIF.',
        '',
        '  " Step 2: Validate credentials in custom Z-table',
        '  SELECT SINGLE * INTO WA_LOGIN',
        '    FROM zmm_rbt_vend_login',
        '    WHERE vendor_id = iv_vendor_id',
        '      AND password  = iv_password',
        "      AND is_active = 'X'.",
        '  IF sy-subrc = 0.',
        "    ev_result  = 'S'.",
        "    ev_message = 'Login successful'.",
        '    UPDATE zmm_rbt_vend_login SET last_login = sy-datum',
        '      WHERE vendor_id = iv_vendor_id.',
        '    COMMIT WORK.',
        '  ELSE.',
        "    ev_result  = 'E'.",
        "    ev_message = 'Invalid credentials or account is inactive'.",
        '  ENDIF.',
        'ENDFUNCTION.',
      ]),
      note('Middleware: auth.controller.js zpassword/zis_active mirror Z-table fields – structure is correct. Replace mock with RFC call when going live.'),
      gap(),

      h2('Step 7 – FM 2: ZMM_RBT_VENDOR_PROFILE  |  Processing Type: RFC  |  FRS 3.2.2'),
      tbl(['Parameter','Direction','Type','Description'],[
        ['IV_VENDOR_ID','Import','LIFNR','Vendor ID'],
        ['IV_COMP_CODE','Import','BUKRS','Company Code'],
        ['ES_PROFILE','Export','ZMM_RBT_PROF_S','Complete vendor profile structure'],
      ],[2200,1400,2200,3226]),
      gap(),
      ...cl([
        'FUNCTION ZMM_RBT_VENDOR_PROFILE.',
        '  DATA: WA_LFA1 TYPE lfa1, WA_LFB1 TYPE lfb1,',
        '        WA_LFM1 TYPE lfm1, WA_ADRC TYPE adrc.',
        '',
        '  SELECT SINGLE * INTO WA_LFA1 FROM lfa1 WHERE lifnr = iv_vendor_id.',
        '  SELECT SINGLE * INTO WA_LFB1 FROM lfb1',
        '    WHERE lifnr = iv_vendor_id AND bukrs = iv_comp_code.',
        '  SELECT SINGLE * INTO WA_LFM1 FROM lfm1 WHERE lifnr = iv_vendor_id.',
        '  SELECT SINGLE * INTO WA_ADRC FROM adrc',
        '    WHERE addrnumber = WA_LFA1-adrnr.',
        '',
        '  es_profile-lifnr     = WA_LFA1-lifnr.',
        '  es_profile-name1     = WA_LFA1-name1.',
        '  es_profile-ort01     = WA_LFA1-ort01.',
        '  es_profile-land1     = WA_LFA1-land1.',
        '  es_profile-stras     = WA_LFA1-stras.',
        "  es_profile-pstlz     = WA_LFA1-pstlz.   \" FIX: postal code",
        '  es_profile-telf1     = WA_LFA1-telf1.',
        '  es_profile-smtp_addr = WA_ADRC-smtp_addr.',
        '  es_profile-waers     = WA_LFB1-waers.',
        '  es_profile-zterm     = WA_LFB1-zterm.',
        '  es_profile-akont     = WA_LFB1-akont.',
        "  es_profile-bukrs     = iv_comp_code.     \" FIX: company code",
        '  es_profile-ekgrp     = WA_LFM1-ekgrp.',
        "  es_profile-stcd1     = WA_LFA1-stcd1.   \" FIX: tax ID",
        'ENDFUNCTION.',
      ]),
      note('Middleware map: LIFNR→vendor_id | NAME1→name | PSTLZ→postal_code | STCD1→tax_id | BUKRS→company_code'),
      note('Frontend fix: add  akont: string  and  ekgrp: string  to VendorProfile interface in vendor.models.ts'),
      gap(),

      h2('Step 8 – FM 3: ZMM_RBT_VENDOR_DASHBOARD  |  RFC  |  FRS 3.2.3'),
      p('BAPIs per FRS: RFQ = BAPI_QUOTATION_GETDETAILEDLIST  |  PO = BAPI_PO_GETDETAIL  |  GR = MSEG direct'),
      tbl(['Parameter','Direction','Type','Description'],[
        ['IV_VENDOR_ID','Import','LIFNR','Vendor ID'],
        ['IV_COMP_CODE','Import','BUKRS','Company Code'],
        ['ET_RFQ','Tables','ZMM_RBT_DASH_T','RFQ documents list'],
        ['ET_PO','Tables','ZMM_RBT_DASH_T','Purchase Order list'],
        ['ET_GR','Tables','ZMM_RBT_DASH_T','Goods Receipt list'],
      ],[2200,1400,2200,3226]),
      gap(),
      ...cl([
        'FUNCTION ZMM_RBT_VENDOR_DASHBOARD.',
        '  DATA: WA_EKKO TYPE ekko, WA_EKPO TYPE ekpo,',
        '        WA_MSEG TYPE mseg, WA_DASH TYPE zmm_rbt_dash_s,',
        '        LOC_EBELN TYPE ebeln.',
        '',
        '  " ===== RFQ (Document Category A) – BAPI_QUOTATION_GETDETAILEDLIST =====',
        '  SELECT ebeln INTO LOC_EBELN FROM ekko',
        "    WHERE lifnr = iv_vendor_id AND bstyp = 'A'.",
        '    SELECT SINGLE * INTO WA_EKKO FROM ekko WHERE ebeln = LOC_EBELN.',
        '    SELECT SINGLE * INTO WA_EKPO FROM ekpo',
        "      WHERE ebeln = LOC_EBELN AND ebelp = '00010'.",
        "    WA_DASH-doc_type = 'RFQ'.",
        '    WA_DASH-ebeln = LOC_EBELN.    WA_DASH-bedat = WA_EKKO-bedat.',
        '    WA_DASH-matnr = WA_EKPO-matnr. WA_DASH-txz01 = WA_EKPO-txz01.',
        '    WA_DASH-menge = WA_EKPO-menge. WA_DASH-meins = WA_EKPO-meins.',
        '    WA_DASH-netpr = WA_EKPO-netpr. WA_DASH-waers = WA_EKKO-waers.',
        "    WA_DASH-eindt = WA_EKPO-eindt.  \" FIX: deadline date",
        '    WA_DASH-elikz = WA_EKPO-elikz.',
        '    APPEND WA_DASH TO et_rfq. CLEAR WA_DASH.',
        '  ENDSELECT.',
        '',
        '  " ===== PO (Document Category F) – BAPI_PO_GETDETAIL =====',
        '  SELECT ebeln INTO LOC_EBELN FROM ekko',
        "    WHERE lifnr = iv_vendor_id AND bstyp = 'F' AND bukrs = iv_comp_code.",
        '    SELECT SINGLE * INTO WA_EKKO FROM ekko WHERE ebeln = LOC_EBELN.',
        '    SELECT SINGLE * INTO WA_EKPO FROM ekpo',
        "      WHERE ebeln = LOC_EBELN AND ebelp = '00010'.",
        "    WA_DASH-doc_type = 'PO'.",
        '    WA_DASH-ebeln = LOC_EBELN.    WA_DASH-bedat = WA_EKKO-bedat.',
        '    WA_DASH-matnr = WA_EKPO-matnr. WA_DASH-txz01 = WA_EKPO-txz01.',
        '    WA_DASH-menge = WA_EKPO-menge. WA_DASH-meins = WA_EKPO-meins.',
        '    WA_DASH-netpr = WA_EKPO-netpr. WA_DASH-waers = WA_EKKO-waers.',
        '    WA_DASH-werks = WA_EKPO-werks.',
        "    WA_DASH-eindt = WA_EKPO-eindt.  \" FIX: delivery date",
        '    WA_DASH-elikz = WA_EKPO-elikz.',
        '    APPEND WA_DASH TO et_po. CLEAR WA_DASH.',
        '  ENDSELECT.',
        '',
        '  " ===== GR (Movement Type 101) =====',
        "  SELECT * INTO WA_MSEG FROM mseg WHERE lifnr = iv_vendor_id AND bwart = '101'.",
        "    WA_DASH-doc_type = 'GR'.",
        "    WA_DASH-mblnr = WA_MSEG-mblnr.  \" FIX: gr_no",
        '    WA_DASH-ebeln = WA_MSEG-ebeln.  WA_DASH-budat = WA_MSEG-budat.',
        '    WA_DASH-matnr = WA_MSEG-matnr.  WA_DASH-menge = WA_MSEG-menge.',
        '    WA_DASH-meins = WA_MSEG-meins.  WA_DASH-werks = WA_MSEG-werks.',
        '    WA_DASH-lgort = WA_MSEG-lgort.',
        "    WA_DASH-bwart = WA_MSEG-bwart.  \" FIX: movement_type",
        '    APPEND WA_DASH TO et_gr. CLEAR WA_DASH.',
        '  ENDSELECT.',
        'ENDFUNCTION.',
      ]),
      note('RFQ map: EBELN→rfq_no | TXZ01→material | EINDT→deadline | NETPR×MENGE→amount | ELIKZ→status'),
      note('PO map:  EBELN→po_no | BEDAT→po_date | EINDT→delivery_date | NETPR×MENGE→net_value | WERKS→plant'),
      note('GR map:  MBLNR→gr_no | EBELN→po_no | BUDAT→gr_date | WERKS→plant | LGORT→storage_loc | BWART→movement_type'),
      gap(),

      h2('Step 9 – FM 4: ZMM_RBT_VENDOR_FINANCIAL  |  RFC  |  FRS 3.2.4'),
      p('FRS Aging Formula: Aging = Billing Date (BLDAT) minus Due Date (ZFBDT)'),
      p('Tables used: BSIK (open items) | BSAK (cleared items) | BKPF + BSEG (memos: KG=Credit, KL=Debit)'),
      tbl(['Parameter','Direction','Type','Description'],[
        ['IV_VENDOR_ID','Import','LIFNR','Vendor ID'],
        ['IV_COMP_CODE','Import','BUKRS','Company Code'],
        ['IV_FISC_YEAR','Import','GJAHR','Fiscal Year'],
        ['ET_INVOICES','Tables','ZMM_RBT_INV_T','Open + cleared invoices with aging'],
        ['ET_MEMO','Tables','ZMM_RBT_MEMO_T','Credit and Debit memos'],
      ],[2200,1400,2200,3226]),
      gap(),
      ...cl([
        'FUNCTION ZMM_RBT_VENDOR_FINANCIAL.',
        '  DATA: IT_BSIK TYPE TABLE OF bsik, IT_BSAK TYPE TABLE OF bsak,',
        '        WA_BSIK TYPE bsik, WA_BSAK TYPE bsak,',
        '        WA_BKPF TYPE bkpf, WA_BSEG TYPE bseg,',
        '        WA_INV  TYPE zmm_rbt_inv_s,',
        '        WA_MEMO TYPE zmm_rbt_memo_s,',
        '        LOC_AGING TYPE i.',
        '',
        '  " ===== OPEN Invoices from BSIK =====',
        '  SELECT * INTO TABLE IT_BSIK FROM bsik',
        '    WHERE lifnr = iv_vendor_id AND bukrs = iv_comp_code AND gjahr = iv_fisc_year.',
        '  LOOP AT IT_BSIK INTO WA_BSIK.',
        '    CLEAR WA_INV.',
        '    LOC_AGING = WA_BSIK-bldat - WA_BSIK-zfbdt.  " FRS: Billing Date - Due Date',
        '    WA_INV-belnr  = WA_BSIK-belnr.',
        "    WA_INV-gjahr  = WA_BSIK-gjahr.   \" FIX",
        '    WA_INV-bldat  = WA_BSIK-bldat.  WA_INV-budat = WA_BSIK-budat.',
        '    WA_INV-ebeln  = WA_BSIK-ebeln.',
        "    WA_INV-lifnr  = WA_BSIK-lifnr.   \" FIX",
        "    WA_INV-blart  = WA_BSIK-blart.   \" FIX",
        '    WA_INV-wrbtr  = WA_BSIK-wrbtr.  WA_INV-waers = WA_BSIK-waers.',
        '    WA_INV-zfbdt  = WA_BSIK-zfbdt.  WA_INV-aging_days = LOC_AGING.',
        '    WA_INV-shkzg  = WA_BSIK-shkzg.  WA_INV-zlsch = WA_BSIK-zlsch.',
        "    WA_INV-mwskz  = WA_BSIK-mwskz.  \" FIX",
        "    WA_INV-xblnr  = WA_BSIK-xblnr.  \" FIX",
        "    WA_INV-sgtxt  = WA_BSIK-sgtxt.  \" FIX",
        "    WA_INV-status = 'O'.             \" FIX: Open",
        '    APPEND WA_INV TO et_invoices.',
        '  ENDLOOP.',
        '',
        '  " ===== CLEARED Invoices from BSAK =====',
        '  SELECT * INTO TABLE IT_BSAK FROM bsak',
        '    WHERE lifnr = iv_vendor_id AND bukrs = iv_comp_code AND gjahr = iv_fisc_year.',
        '  LOOP AT IT_BSAK INTO WA_BSAK.',
        '    CLEAR WA_INV.',
        '    LOC_AGING = WA_BSAK-bldat - WA_BSAK-zfbdt.',
        '    WA_INV-belnr  = WA_BSAK-belnr.',
        "    WA_INV-gjahr  = WA_BSAK-gjahr.   \" FIX",
        '    WA_INV-bldat  = WA_BSAK-bldat.  WA_INV-budat = WA_BSAK-budat.',
        '    WA_INV-ebeln  = WA_BSAK-ebeln.',
        "    WA_INV-lifnr  = WA_BSAK-lifnr.   \" FIX",
        "    WA_INV-blart  = WA_BSAK-blart.   \" FIX",
        '    WA_INV-wrbtr  = WA_BSAK-wrbtr.  WA_INV-waers = WA_BSAK-waers.',
        '    WA_INV-zfbdt  = WA_BSAK-zfbdt.  WA_INV-aging_days = LOC_AGING.',
        '    WA_INV-shkzg  = WA_BSAK-shkzg.  WA_INV-zlsch = WA_BSAK-zlsch.',
        "    WA_INV-mwskz  = WA_BSAK-mwskz.  \" FIX",
        "    WA_INV-xblnr  = WA_BSAK-xblnr.  \" FIX",
        "    WA_INV-sgtxt  = WA_BSAK-sgtxt.  \" FIX",
        '    WA_INV-augdt  = WA_BSAK-augdt.',
        "    WA_INV-status = 'C'.             \" FIX: Cleared",
        '    APPEND WA_INV TO et_invoices.',
        '  ENDLOOP.',
        '',
        '  " ===== Credit/Debit Memos from BKPF + BSEG (KG/KL) =====',
        '  SELECT * INTO WA_BKPF FROM bkpf',
        "    WHERE bukrs = iv_comp_code AND gjahr = iv_fisc_year AND blart IN ('KG','KL').",
        '    SELECT SINGLE * INTO WA_BSEG FROM bseg',
        '      WHERE belnr = WA_BKPF-belnr AND bukrs = WA_BKPF-bukrs',
        "        AND gjahr = WA_BKPF-gjahr AND buzei = '001'.",
        '    IF WA_BSEG-lifnr = iv_vendor_id.',
        '      CLEAR WA_MEMO.',
        '      WA_MEMO-belnr = WA_BKPF-belnr.  WA_MEMO-bldat = WA_BKPF-bldat.',
        '      WA_MEMO-budat = WA_BKPF-budat.  WA_MEMO-blart = WA_BKPF-blart.',
        '      WA_MEMO-wrbtr = WA_BSEG-wrbtr.  WA_MEMO-waers = WA_BKPF-waers.',
        '      WA_MEMO-sgtxt = WA_BSEG-sgtxt.  WA_MEMO-shkzg = WA_BSEG-shkzg.',
        '      APPEND WA_MEMO TO et_memo.',
        '    ENDIF.',
        '  ENDSELECT.',
        'ENDFUNCTION.',
      ]),
      note('Middleware map: WRBTR→dmbtr | ZFBDT→faedt | STATUS O→Open / C→Cleared'),
      note('Aging buckets in middleware: <=30 Days | 31-60 Days | 61-90 Days | >90 Days'),
      note('getMemos: use ET_MEMO directly from RFC response when live (currently filters invoiceData)'),
      gap(),

      h2('Step 10 – Adobe Form for Invoice Receipt  |  Transaction: SFP  |  FRS 3.2.4b'),
      p('Form: ZF_MM_RBT_VEND_INVOICE     Interface: ZIF_MM_RBT_VEND_INVOICE'),
      p('1.  SFP → Create Interface: ZIF_MM_RBT_VEND_INVOICE → add input IS_INVOICE (type ZMM_RBT_INV_S)'),
      p('2.  Create Form: ZF_MM_RBT_VEND_INVOICE → reference the interface above'),
      p('3.  Layout: display BELNR, BLDAT, ZFBDT, WRBTR+WAERS, EBELN, XBLNR, SGTXT, AGING_DAYS, ZLSCH'),
      p('4.  Activate form and interface'),
      p('5.  Middleware endpoint /api/financial/invoice/:belnr/pdf → calls FP_FUNCTION_MODULE_NAME + FP_EXECUTE_SUBRC → streams PDF to Angular'),
      gap(),

      h2('Step 11 – Test All FMs  |  SE37 → F8'),
      tbl(['FM Name','Test Input','Expected Result'],[
        ['ZMM_RBT_VENDOR_LOGIN','Valid vendor ID + correct password','EV_RESULT = S'],
        ['ZMM_RBT_VENDOR_LOGIN','Valid vendor ID + wrong password','EV_RESULT = E'],
        ['ZMM_RBT_VENDOR_LOGIN','Non-existent vendor ID','EV_RESULT = E (LFA1 fails)'],
        ['ZMM_RBT_VENDOR_PROFILE','Valid vendor ID + company code','ES_PROFILE populated incl PSTLZ, STCD1'],
        ['ZMM_RBT_VENDOR_DASHBOARD','Valid vendor ID + company code','ET_RFQ/PO with EINDT, ET_GR with MBLNR + BWART'],
        ['ZMM_RBT_VENDOR_FINANCIAL','Valid vendor ID + company code + year','ET_INVOICES with all [FIX] fields + STATUS, ET_MEMO filled'],
      ],[3000,3200,3026]),
      gap(),

      h2('Step 12 – Expose as RFC Web Service  |  SOAMANAGER'),
      p('1.  SOAMANAGER → Web Service Configuration → Create → Based on Existing RFC/BAPI'),
      p('2.  Search ZMM_RBT_VENDOR_* → register each FM as a Web Service'),
      p('3.  Security: Basic Authentication (production) | None (development)'),
      p('4.  Note the WSDL URL for each service → test with SOAPUI or Postman'),
      gap(),

      // 5
      h1('5. Complete Alignment Report  –  Frontend + Middleware + SAP Backend'),

      h2('5.1 Login / Authentication'),
      tbl(['Check','Status','Note'],[
        ['Vendor ID check in LFA1','Aligned','auth.controller.js sends vendor_id correctly'],
        ['Password verified in Z-table','Aligned','zpassword & zis_active mirror Z-table fields exactly'],
        ['JWT returned on success','Aligned','Token contains vendor_id and name'],
        ['Live SAP RFC call','Pending','Replace mock lookup with ZMM_RBT_VENDOR_LOGIN RFC call when going live'],
      ],[3500,1800,3726]),
      gap(),

      h2('5.2 Vendor Profile'),
      tbl(['Check','Status','Note'],[
        ['Name, city, country, street, phone, email, currency, payment terms','Aligned','Direct SAP mapping – no issues'],
        ['Postal code (PSTLZ)','Fixed','Added to ZMM_RBT_PROF_S + FM source code'],
        ['Company code (BUKRS)','Fixed','Added to ZMM_RBT_PROF_S + FM source code'],
        ['Tax ID (STCD1)','Fixed','Added to ZMM_RBT_PROF_S + FM source code'],
        ['Reconciliation account (AKONT)','Fixed','In FM – also add akont:string to VendorProfile TS interface'],
        ['Purchasing group (EKGRP)','Fixed','In FM – also add ekgrp:string to VendorProfile TS interface'],
        ['bank_account field','Not from standard SAP','Read from LFBK table if required'],
        ['category, rating fields','Not from SAP','Portal-level custom fields only'],
      ],[3200,1600,4226]),
      gap(),

      h2('5.3 RFQ'),
      tbl(['Check','Status','Note'],[
        ['RFQ number (EBELN)','Aligned','Maps to rfq_no'],
        ['Material description (TXZ01), Qty, Unit','Aligned','Direct mapping'],
        ['Deadline date (EINDT)','Fixed','Added EINDT to ZMM_RBT_DASH_S'],
        ['Total amount','Fixed','Middleware computes NETPR × MENGE'],
        ['Status (Open/Closed)','Fixed','Middleware derives from ELIKZ flag'],
        ['BAPI_QUOTATION_GETDETAILEDLIST','Aligned','Explicitly referenced per FRS 3.2.3c'],
      ],[3000,1800,4226]),
      gap(),

      h2('5.4 Purchase Order'),
      tbl(['Check','Status','Note'],[
        ['PO number, material, qty, unit, date, currency, plant','Aligned','Direct mapping'],
        ['Delivery date (EINDT)','Fixed','Added EINDT to ZMM_RBT_DASH_S (same field as RFQ deadline)'],
        ['Net value (total)','Fixed','Middleware computes NETPR × MENGE'],
        ['Status (Open/Partially Delivered/Closed)','Fixed','Middleware derives from ELIKZ'],
        ['BAPI_PO_GETDETAIL','Aligned','Explicitly referenced per FRS 3.2.3b'],
      ],[3000,1800,4226]),
      gap(),

      h2('5.5 Goods Receipt'),
      tbl(['Check','Status','Note'],[
        ['PO ref, material, qty, unit, date, plant, storage location','Aligned','Direct mapping from MSEG'],
        ['GR document number (MBLNR)','Fixed','Added MBLNR to ZMM_RBT_DASH_S → maps to gr_no'],
        ['Movement type (BWART)','Fixed','Added BWART to ZMM_RBT_DASH_S → maps to movement_type'],
      ],[3000,1800,4226]),
      gap(),

      h2('5.6 Invoice and Aging'),
      tbl(['Check','Status','Note'],[
        ['Doc number, billing date, posting date, PO ref, amount, currency, due date','Aligned','Direct mapping'],
        ['Aging = Billing Date minus Due Date','Fixed','BLDAT - ZFBDT per FRS 3.2.4 formula'],
        ['Fiscal year (GJAHR)','Fixed','Added to ZMM_RBT_INV_S'],
        ['Vendor number (LIFNR)','Fixed','Added to ZMM_RBT_INV_S'],
        ['Document type (BLART)','Fixed','Added to ZMM_RBT_INV_S'],
        ['Tax code (MWSKZ)','Fixed','Added to ZMM_RBT_INV_S'],
        ['External reference (XBLNR)','Fixed','Added to ZMM_RBT_INV_S'],
        ['Item text (SGTXT)','Fixed','Added to ZMM_RBT_INV_S'],
        ['Status (Open/Cleared)','Fixed','Derived in FM: O from BSIK, C from BSAK'],
        ['Field name faedt','Fixed','Middleware maps SAP field ZFBDT → faedt for frontend'],
        ['Field name dmbtr','Fixed','Middleware maps SAP field WRBTR → dmbtr for frontend'],
        ['Aging bucket','Fixed','Computed in middleware from aging_days value'],
      ],[2800,1600,4626]),
      gap(),

      h2('5.7 Credit / Debit Memo'),
      tbl(['Check','Status','Note'],[
        ['Doc number, date, type KG/KL, amount, currency, text','Aligned','Direct mapping from BKPF/BSEG'],
        ['SHKZG (Debit/Credit indicator)','Fixed','In ZMM_RBT_MEMO_S – add shkzg:string to frontend Memo interface'],
        ['Dedicated TypeScript Memo interface','Fixed','Add new Memo interface to vendor.models.ts (see Section 7)'],
        ['getMemos KG/KL filter','Aligned','Matches SAP document types exactly'],
      ],[3000,1800,4226]),
      gap(),

      h2('5.8 Adobe Form (Invoice Receipt)'),
      tbl(['Check','Status','Note'],[
        ['Invoice receipt as Adobe Form','Aligned','ZF_MM_RBT_VEND_INVOICE via SFP per FRS 3.2.4b'],
        ['PDF middleware endpoint','Aligned','/api/financial/invoice/:belnr/pdf stub ready – connect to form FM'],
        ['FRS 3.2.4b requirement','Covered','Form uses ZMM_RBT_INV_S as input interface'],
      ],[3000,1800,4226]),
      gap(),

      // 6
      h1('6. Key SAP Tables Reference'),
      tbl(['Table','Module','Description','Used In'],[
        ['LFA1','MM','Vendor Master General Data','Login (LFA1 check), Profile'],
        ['LFB1','MM/FI','Vendor Master Company Code Data','Profile (WAERS, ZTERM, AKONT)'],
        ['LFM1','MM','Vendor Master Purchasing Org Data','Profile (EKGRP)'],
        ['ADRC','BASIS','Address Details','Profile (SMTP_ADDR, PSTLZ)'],
        ['LFBK','MM','Vendor Bank Details','Profile – bank_account (if required)'],
        ['EKKO','MM','Purchasing Document Header','Dashboard – RFQ, PO'],
        ['EKPO','MM','Purchasing Document Item','Dashboard – EINDT for RFQ/PO'],
        ['MSEG','MM','Material Document Segment','Dashboard – GR (MBLNR, BWART)'],
        ['BSIK','FI','Vendor Open Items (unpaid)','Financial – Open invoices'],
        ['BSAK','FI','Vendor Cleared Items (paid)','Financial – Cleared invoices'],
        ['BKPF','FI','Accounting Document Header','Financial – Memos (KG, KL)'],
        ['BSEG','FI','Accounting Document Line Items','Financial – Memo amounts'],
      ],[1500,1100,3100,3326]),
      gap(),

      // 7
      h1('7. Frontend TypeScript Fixes  –  vendor.models.ts'),

      h2('7.1 Add to VendorProfile interface'),
      ...cl([
        'export interface VendorProfile {',
        '  // ... existing fields ...',
        '  akont: string;   // Reconciliation Account (from LFB1)',
        '  ekgrp: string;   // Purchasing Group (from LFM1)',
        '  // tax_id already present – maps from SAP field STCD1',
        '}',
      ]),
      gap(),

      h2('7.2 Add new Memo interface'),
      ...cl([
        'export interface Memo {',
        '  belnr: string;',
        '  bldat: string;',
        '  budat: string;',
        '  blart: string;   // KG = Credit Memo, KL = Debit Memo',
        '  wrbtr: number;',
        '  waers: string;',
        '  sgtxt: string;',
        '  shkzg: string;   // H = Debit, S = Credit',
        '}',
      ]),
      gap(),

      h2('7.3 GoodsReceipt – fields now available from SAP'),
      p('gr_no        →  maps from MBLNR  (field added to ZMM_RBT_DASH_S – Fixed)'),
      p('movement_type →  maps from BWART  (field added to ZMM_RBT_DASH_S – Fixed)'),
      p('All other GoodsReceipt interface fields were already aligned with SAP.'),
      gap(),
      h2('7.4 Invoice field name mapping (no TS change needed)'),
      p('faedt  ←  SAP field ZFBDT   (middleware maps ZFBDT → faedt before sending to frontend)'),
      p('dmbtr  ←  SAP field WRBTR   (middleware maps WRBTR → dmbtr before sending to frontend)'),
    ]
  }]
});

Packer.toBuffer(doc).then(buf => {
  fs.writeFileSync('SAP_Backend_Vendor_Portal_RBT.docx', buf);
  console.log('DONE – file saved');
}).catch(e => { console.error('ERROR:', e.message); process.exit(1); });
